import { makeStyles } from "../hooks/makeStyles";

export const useLoginStyles = makeStyles((theme) => ({
  safeArea: { flex: 1 },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    padding: theme.spacing.lg,
    paddingBottom: 80,
  },
  gradient: { position: "absolute", left: 0, right: 0, top: 0, bottom: 0 },
  bgCircleOne: {
    position: "absolute",
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: theme.colors.primary,
    opacity: 0.06,
    top: -80,
    left: -40,
  },
  bgCircleTwo: {
    position: "absolute",
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: theme.colors.primaryDark,
    opacity: 0.05,
    bottom: -50,
    right: -20,
  },
  card: {
    width: "100%",
    maxWidth: 440,
    alignSelf: "center",
    backgroundColor: theme.colors.surface,
    paddingVertical: 36,
    paddingHorizontal: 28,
    borderRadius: 20,
    // subtle elevated card
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 6,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.03)",
  },
  header: { alignItems: "center", marginBottom: 28 },
  logo: {
    fontSize: 36,
    fontWeight: "900",
    color: theme.colors.text,
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 13,
    color: theme.colors.textMuted,
    marginTop: 8,
    textAlign: "center",
    maxWidth: 300,
  },
  inputContainer: { marginBottom: 18 },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.colors.background,
    borderRadius: 14,
    paddingHorizontal: 14,
    marginBottom: 14,
    height: 56,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  inputRowElevated: {
    // subtle inner elevation for inputs
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 1,
  },
  inputIcon: { marginRight: 12, opacity: 0.6 },
  input: {
    flex: 1,
    height: "100%",
    padding: 0,
    fontSize: 16,
    color: theme.colors.text,
  },
  forgotPassword: {
    alignSelf: "flex-end",
    color: theme.colors.primary,
    fontSize: 13,
    marginTop: -8,
    marginBottom: 16,
    fontWeight: "600",
  },
  button: {
    height: 56,
    backgroundColor: theme.colors.primary,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 8,
  },
  buttonDisabled: { backgroundColor: theme.colors.border, shadowOpacity: 0 },
  pressed: { opacity: 0.9, transform: [{ scale: 0.98 }] },
  buttonText: { color: "#fff", fontWeight: "700", fontSize: 16 },
  errorText: {
    color: theme.colors.danger,
    marginBottom: 16,
    textAlign: "center",
  },
  divider: { flexDirection: "row", alignItems: "center", marginVertical: 28 },
  line: {
    flex: 1,
    height: 1,
    backgroundColor: theme.colors.border,
    opacity: 0.5,
  },
  dividerText: {
    marginHorizontal: 16,
    color: theme.colors.textMuted,
    fontSize: 12,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  socialRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
  },
  iconButtonLarge: {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: theme.colors.surface,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
  },
  googleIcon: { backgroundColor: "#fff" },
  facebookIcon: { backgroundColor: "#1877F2" },
  row: { flexDirection: "row", justifyContent: "center", marginTop: 36 },
  smallText: { color: theme.colors.textMuted, fontSize: 14 },
  linkText: {
    color: theme.colors.primary,
    fontWeight: "700",
    fontSize: 14,
    marginLeft: 4,
  },
}));
