import type { TextStyle } from "react-native";
import { makeStyles } from "../hooks/makeStyles";

export const useLoginStyles = makeStyles((theme) => ({
  safeArea: { flex: 1 },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    padding: theme.spacing.lg,
    paddingBottom: 80,
  },
  gradient: { position: "absolute", left: 0, right: 0, top: 0, bottom: 0 },
  bgCircleOne: {
    position: "absolute",
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: theme.colors.primary,
    opacity: 0.06,
    top: -80,
    left: -40,
  },
  bgCircleTwo: {
    position: "absolute",
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: theme.colors.primaryDark,
    opacity: 0.05,
    bottom: -50,
    right: -20,
  },
  card: {
    width: "100%",
    maxWidth: 440,
    alignSelf: "center",
    backgroundColor: theme.colors.surface,
    paddingVertical: theme.spacing.xl,
    paddingHorizontal: theme.spacing.lg,
    borderRadius: theme.radius.lg,
    // subtle elevated card
    ...theme.elevation.mid,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  header: { alignItems: "center", marginBottom: theme.spacing.lg },
  logo: {
    fontSize: theme.typography.fontSizes.xl,
    fontWeight: theme.typography.fontWeights.bold as TextStyle["fontWeight"],
    color: theme.colors.text,
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: theme.typography.fontSizes.sm,
    color: theme.colors.textMuted,
    marginTop: theme.spacing.sm,
    textAlign: "center",
    maxWidth: 300,
  },
  inputContainer: { marginBottom: theme.spacing.md },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.colors.background,
    borderRadius: theme.radius.md,
    paddingHorizontal: theme.spacing.md,
    marginBottom: theme.spacing.md,
    height: 56,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  inputRowElevated: {
    // subtle inner elevation for inputs
    ...theme.elevation.low,
  },
  inputIcon: { marginRight: theme.spacing.md, opacity: 0.6 },
  input: {
    flex: 1,
    height: "100%",
    padding: 0,
    fontSize: theme.typography.fontSizes.md,
    color: theme.colors.text,
  },
  forgotPassword: {
    alignSelf: "flex-end",
    color: theme.colors.primary,
    fontSize: theme.typography.fontSizes.sm,
    marginTop: -8,
    marginBottom: theme.spacing.md,
    fontWeight: theme.typography.fontWeights.medium as TextStyle["fontWeight"],
  },
  button: {
    height: 56,
    backgroundColor: theme.colors.primary,
    borderRadius: theme.radius.lg,
    justifyContent: "center",
    alignItems: "center",
    marginTop: theme.spacing.sm,
  },
  buttonDisabled: { backgroundColor: theme.colors.border, shadowOpacity: 0 },
  pressed: { opacity: 0.9, transform: [{ scale: 0.98 }] },
  buttonText: {
    color: theme.getContrastText(theme.colors.primary),
    fontWeight: "700",
    fontSize: theme.typography.fontSizes.md,
  },
  errorText: {
    color: theme.colors.danger,
    marginBottom: theme.spacing.md,
    textAlign: "center",
  },
  divider: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: theme.spacing.lg,
  },
  line: {
    flex: 1,
    height: 1,
    backgroundColor: theme.colors.border,
    opacity: 0.5,
  },
  dividerText: {
    marginHorizontal: theme.spacing.md,
    color: theme.colors.textMuted,
    fontSize: theme.typography.fontSizes.xs,
    fontWeight: theme.typography.fontWeights.bold as TextStyle["fontWeight"],
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  socialRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: theme.spacing.md,
  },
  iconButtonLarge: {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: theme.colors.surface,
    ...theme.elevation.mid,
  },
  googleIcon: { backgroundColor: theme.colors.google },
  facebookIcon: { backgroundColor: theme.colors.facebook },
  row: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: theme.spacing.xl,
  },
  smallText: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.fontSizes.sm,
  },
  linkText: {
    color: theme.colors.primary,
    fontWeight: theme.typography.fontWeights.bold as TextStyle["fontWeight"],
    fontSize: theme.typography.fontSizes.sm,
    marginLeft: theme.spacing.xs,
  },
}));
